# Site settings
title: Allan Zhao
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Allan Zhao's personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://allanzhao.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: allanzhao

# Build settings
markdown: kramdown
theme: tactile
